# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kategoriview.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector as mc
from PyQt5.QtWidgets import QTableWidgetItem


class Ui_Kategori(object):
    def setupUi(self, Kategori):
        Kategori.setObjectName("Kategori")
        Kategori.resize(400, 418)
        self.lineEditId = QtWidgets.QLineEdit(Kategori)
        self.lineEditId.setGeometry(QtCore.QRect(140, 20, 201, 20))
        self.lineEditId.setObjectName("lineEditId")
        self.labelName = QtWidgets.QLabel(Kategori)
        self.labelName.setGeometry(QtCore.QRect(30, 50, 91, 16))
        self.labelName.setObjectName("labelName")
        self.labelld = QtWidgets.QLabel(Kategori)
        self.labelld.setGeometry(QtCore.QRect(30, 20, 71, 16))
        self.labelld.setObjectName("labelld")
        self.pushButtonInsert = QtWidgets.QPushButton(Kategori)
        self.pushButtonInsert.setGeometry(QtCore.QRect(30, 100, 311, 23))
        self.pushButtonInsert.setObjectName("pushButtonInsert")
        self.lineEditName = QtWidgets.QLineEdit(Kategori)
        self.lineEditName.setGeometry(QtCore.QRect(140, 50, 201, 20))
        self.lineEditName.setObjectName("lineEditName")
        self.labelresult = QtWidgets.QLabel(Kategori)
        self.labelresult.setGeometry(QtCore.QRect(20, 130, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.labelresult.setFont(font)
        self.labelresult.setObjectName("labelresult")
        self.pushButtonLoad = QtWidgets.QPushButton(Kategori)
        self.pushButtonLoad.setGeometry(QtCore.QRect(20, 380, 351, 23))
        self.pushButtonLoad.setObjectName("pushButtonLoad")
        self.tableWidget = QtWidgets.QTableWidget(Kategori)
        self.tableWidget.setGeometry(QtCore.QRect(20, 170, 351, 192))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.pushButtonInsert.clicked.connect(self.insertKategori)
        self.pushButtonLoad.clicked.connect(self.loadKategori)
        self.tableWidget.cellClicked.connect(self.getByid)
        
        

        self.retranslateUi(Kategori)
        QtCore.QMetaObject.connectSlotsByName(Kategori)
        
    def getByid(self,row,column):
        try:    
            iditem = self.tableWidget.item(row,0)
            nameitem = self.tableWidget.item(row,1)
            if iditem :
                valueid = iditem.text()
                valuename = nameitem.text()
                self.lineEditId.setText(valueid)
                self.lineEditName.setText(valuename)
            self.labelresult.setText(" ID Data Kategori")
        except mc.Error as Err:
            self.labelresult.setText("Data Kategori Gagal")
        
    def insertKategori(self):
            try:
                mydb = mc.connect(
                    host ="localhost",
                    user ="root",
                    password ="",
                    database ="db_visual"
                )
                
                cursor = mydb.cursor()
                idkat = self.lineEditId.text()
                namekat = self.lineEditName.text()
                
                sql = "INSERT INTO kategori (id,name) VALUES (%s,%s)"
                val = (idkat,namekat)
                cursor.execute(sql,val)
                mydb.commit()
                self.labelresult.setText("Data Kategori Berhasil Disimpan")
                self.lineEditId.setText("")
                self.lineEditName.setText("")
            except mc.Error as e:
                self.labelresult.setText("Data Kategori Gagal Disimpan")    
                
    def loadKategori(self):
            try:
                mydb = mc.connect(
                    host ="localhost",
                    user ="root",
                    password ="",
                    database ="db_visual"
                )
                mycursor = mydb.cursor()
                mycursor.execute("SELECT * FROM kategori ORDER BY ID ASC")
                result = mycursor.fetchall()
                self.tableWidget.setRowCount(0)
                for row_number, row_data in enumerate(result):
                    self.tableWidget.insertRow(row_number)
                    for column_number, data in enumerate(row_data):
                        self.tableWidget.setItem(row_number,column_number,
QTableWidgetItem(str(data)))
                self.labelresult.setText("Data Kategori Berhasil Ditampilkan")
            except mc.Error as err:
                self.labelresult.setText("Data Kategori Gagal DiLoad")            
                

    def retranslateUi(self, Kategori):
        _translate = QtCore.QCoreApplication.translate
        Kategori.setWindowTitle(_translate("Kategori", "Form"))
        self.labelName.setText(_translate("Kategori", "NAMA KATEGORI"))
        self.labelld.setText(_translate("Kategori", "ID KATEGORI"))
        self.pushButtonInsert.setText(_translate("Kategori", "insert data"))
        self.labelresult.setText(_translate("Kategori", "TextLabel"))
        self.pushButtonLoad.setText(_translate("Kategori", "Load Data"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Kategori", "No"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Kategori", "Name Kategori"))
        self.pushButtonLoad.setText(_translate("Kategori", "LOAD DATA"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Kategori = QtWidgets.QWidget()
    ui = Ui_Kategori()
    ui.setupUi(Kategori)
    Kategori.show()
    sys.exit(app.exec_())
