# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kategori.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector as mc
from PyQt5.QtWidgets import QTableWidgetItem


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.labelld = QtWidgets.QLabel(Form)
        self.labelld.setGeometry(QtCore.QRect(60, 50, 71, 16))
        self.labelld.setObjectName("labelld")
        self.labelName = QtWidgets.QLabel(Form)
        self.labelName.setGeometry(QtCore.QRect(60, 80, 91, 16))
        self.labelName.setObjectName("labelName")
        self.lineEditId = QtWidgets.QLineEdit(Form)
        self.lineEditId.setGeometry(QtCore.QRect(170, 50, 201, 20))
        self.lineEditId.setObjectName("lineEditId")
        self.lineEditName = QtWidgets.QLineEdit(Form)
        self.lineEditName.setGeometry(QtCore.QRect(170, 80, 201, 20))
        self.lineEditName.setObjectName("lineEditName")
        self.pushButtonInsert = QtWidgets.QPushButton(Form)
        self.pushButtonInsert.setGeometry(QtCore.QRect(60, 130, 311, 23))
        self.pushButtonInsert.setObjectName("pushButtonInsert")
        self.labelresult = QtWidgets.QLabel(Form)
        self.labelresult.setGeometry(QtCore.QRect(60, 190, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.labelresult.setFont(font)
        self.labelresult.setObjectName("labelresult")
        self.pushButtonInsert.clicked.connect(self.insertkategori)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.labelld.setText(_translate("Form", "ID KATEGORI"))
        self.labelName.setText(_translate("Form", "NAMA KATEGORI"))
        self.pushButtonInsert.setText(_translate("Form", "insert data"))
        self.labelresult.setText(_translate("Form", "TextLabel"))
        
    def insertkategori(self):
        try:
            mydb = mc.connect(
            host ="localhost",
            user ="root",
            password ="",
            database ="db_visual"
            )
            
            cursor = mydb.cursor()
            idkat = self.lineEditId.text()
            namekat = self.lineEditName.text()
            
            sql = "INSERT INTO kategori (id,name) VALUES (%s,%s)"
            val = (idkat,namekat)
            cursor.execute(sql,val)
            mydb.commit()
            self.labelresult.setText("Data Kategori Berhasil Disimpan")

            self.lineEditId.setText("")
            self.lineEditName.setText("")
        except mc.Error as e:
            self.labelresult.setText("Data Kategori Gagal Disimpan")
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
